### ISSUE TITLE
Too much power for DEPLOYER?

### ISSUE THREAD

**Issue by t4sk** [vetherasset/vaderprotocol-contracts#120]
Is this too much power for `DEPLOYER`? `DEPLOYER` can do everything that the DAO can.

https://github.com/vetherasset/vaderprotocol-contracts/blob/main/contracts/Vader.sol#L44

**Comment by Mervyn853** [comment]
Might want to put deployer behind a 24 hour time lock @strictly-scarce

**Comment by 0x1d00ffff** [comment]
What about adding functions changeDeployer / purgeDeployer? It is unlikely the DAO will be able to react to anything within 24 hours, anyways. 

What is the intention of the deployer access? I'd guess the DAO would want it enabled until the protocol is more mature.
