### ISSUE TITLE
Vader redeem can be claimed by other accounts

### ISSUE THREAD

**Issue by t4sk** [vetherasset/vaderprotocol-contracts#122]
https://github.com/vetherasset/vaderprotocol-contracts/blob/main/contracts/Vader.sol#L252-L264

1. Alice sends USDV to Vader
2. Bob sees `USDV.balanceOf(Vader)` is greater than 0, calls `Vader.redeem()`

Bob redeemed Alice's USDV :(

**Comment by strictly-scarce** [comment]
This is intended behaviour, similiar to how uniswap works
