### ISSUE TITLE
USDV.convert should be disabled if Vader not minting?

### ISSUE THREAD

**Issue by t4sk** [vetherasset/vaderprotocol-contracts#123]
https://github.com/vetherasset/vaderprotocol-contracts/blob/main/contracts/USDV.sol#L166-L184

`USDV.convert` should be disabled if `Vader` is not minting. Otherwise, users can send Vader to USDV contract for 0 USDV in return

**Comment by Mervyn853** [comment]
Hey @t4sk for your flagged issues, could you implement a fix and file a PR for @strictly-scarce to review?

**Comment by 0x1d00ffff** [comment]
closed by pr #154
