### ISSUE TITLE
Consider preferring `constructor` to `init`

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#132]
>With regards to the init pattern, in general the init pattern is utilized when upgrade-ability or a proxy-pattern is desired. In other cases, a constructor is much more sensible and in most cases much more gas efficient as it permits the usage of the immutable mutability specifier, whereby assignments that only occur during a constructor are aggressively optimized and replaced with literals wherever they are used thus not needing the SLOAD gas cost.

**Comment by strictly-scarce** [comment]
* Put all init's of parameters into constructor
* Only use the Init for setting the address of VADER
* use a `onlyDeployer()` modifier, which checks for `iVADER(VADER).deployer()`
