### ISSUE TITLE
`transferTo` considered inferior to alternatives

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#133]
>The `transferTo` pattern should be deprecated from the codebase as it utilizes `tx.origin`. While I understand the gas concern, the `approveAndCall` pattern is much more strongly recommended and can be used once (for setting an unlimited approval) and then a conventional function call can be used. 
>The EIP-3074 introduced by the London fork will allow contracts to act on behalf of EOAs based on on-chain signatures. By utilizing the `tx.origin` in your case, users can be easily fooled to interact with a seemingly innocuous contract that will consequently drain their funds as they can obfuscate the call deep in the call chain. 
>The `approveAndCall` is a much safer pattern to utilize and would incur an extra gas cost only on the first invocation to store the unlimited approval.

**Comment by strictly-scarce** [comment]
Will be removing #156
