### ISSUE TITLE
`isMature` inadequate

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#134]
>The `isMature` function flash loan protection is incorrect for a number of reasons. Firstly, it is already susceptible to MEV-based attacks whereby miners are bribed to order transactions and thus can conduct "organic" flash loans. Secondly, after the EIP-3074 this measure can be easily bypassed as the `tx.origin` can be arbitrarily changed.

**Comment by strictly-scarce** [comment]
Will be removing as to #157
