### ISSUE TITLE
`_checkEmission` `nextEraTime` inadequate

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#136]
>The `nextEraTime` calculation within `_checkEmission` of `Vader.sol` does not properly calculate the next era time as it can bypass multiple eras in case of inactivity in between invocations. We advise this to either be considered or assimilated in the code by properly accounting for skipped eras, if any.

**Comment by strictly-scarce** [comment]
It's not really relevant if an Era is skipped, just the emissions change slightly.
