### ISSUE TITLE
misc code critique for consideration

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#140]
From issue 312 in the recent audit repo.

>Finally, in `Pools.sol`, `Vault.sol` and `Router.sol` there are these methods:

```
function UTILS() public view returns (address) {
    return iVADER(VADER).UTILS();
}
function DAO() public view returns (address) {
    return iVADER(VADER).DAO();
}
```

>Why `Utils` is a contract and not a library?
>Why not to store the value in the contract and when it changes in Vader to change it? This way you reduce gas for the calls between contracts.

**Comment by strictly-scarce** [comment]
hmmm. 

This changes the relationship, from the DAO being the source of truth, to instead the DAO telling each contract what the latest truth is.

What is the gas savings?

**Comment by 0xBrian** [comment]
Let's not mess around with this now. Seems too invasive for too little gain.
