### ISSUE TITLE
`DAO.sol`: `finaliseProposal` possibly needless `!hasQuorum` check

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#143]
In the recent audit, three auditors (issues 186, 234, and 276) suggested removing the `!hasQuorum` check from `finaliseProposal`. Please advise.

**Comment by strictly-scarce** [comment]
yeah not sure why it's there, remove

**Comment by 0xBrian** [comment]
Fixed in #158
