### ISSUE TITLE
`Vether.sol`: possibly needless `require` due to Solidity 0.8.x overflow behavior

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#144]
In the recent audit, issue 190 suggests there may be no need for `Vether.sol:90`

```
require(_balances[_to] + _value >= _balances[_to], "Balance overflow");
```

Not sure I agree, but sending it to you for advice.

**Comment by strictly-scarce** [comment]
it doesn't need it, apart from having a nice `insufficient balance` error message returned, instead of reverting in silence. So I agree with auditor to put it in

**Comment by strictly-scarce** [comment]
Not relevant, since refers to Vether which is deployed
