### ISSUE TITLE
`USDV.sol`: `getFunds` possibly too general

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#146]
In the recent audit, issue 263 points out that `USDV.sol` `getFunds` is too general; it is passed in a token, but it is only used in one way, and is marked `internal`, so maybe it could be simplified. Please advise.

**Comment by strictly-scarce** [comment]
will refactor this

**Comment by strictly-scarce** [comment]
addressed in #157
