### ISSUE TITLE
Router: `swapWithSynthsWithLimit` should use return value of `moveTokenToPools`

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#199]
See `ROU-01M`.

**Comment by strictly-scarce** [comment]
The `moveTokenToPools()` function does exactly that, just moves the token. 

The POOLS contract inspects its own balance and performs the swap/mint/burn. 

The ROUTER does not perform any logic on the actual moved value. Even if a FoT token was used it would not impact the Router.
