### ISSUE TITLE
Pools: `deploySynth` checks inadequate

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#200]
> The `!isAnchor` evaluation performed within `deploySynth` does not properly guard the function as one can create a synth first and then add it as an anchor via the `addLiquidity` call.

See `POO-04S`.

**Comment by strictly-scarce** [comment]
Anchors are just a class of pools that have VADER as base. It's just important that synths of stablecoins don't become widely used, so added additional check to stop an Anchor being added to the TWAP if also a synth
