### ISSUE TITLE
Router: TWAP should be updated elsewhere

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#201]
> The TWAP price of VADER to USD which is in turn retrieved by the Anchor feeds in `getAnchorPrice` should be updated via the pool itself rather than the router as users are able to directly interface with the pool thus changing the prices without the price update being necessarily reflected in the router.

See `ROU-02S`.

**Comment by strictly-scarce** [comment]
Closed with #223
