### ISSUE TITLE
Pools: `_addLiquidity` may need more checks on `base`

### ISSUE THREAD

**Issue by 0xBrian** [vetherasset/vaderprotocol-contracts#202]
> The `else` branch of the first if statement within `_addLiquidity` assumes that if the `base` is not VADER it will be USDV which may not be the case as the `require` check of the function simply checks if the ROUTER validates the `isBase` call rather than doing explicit checks like the second `require` check.

See `POO-02M`.

**Comment by strictly-scarce** [comment]
Router knows USDV and VADER, and does the check in `isBase()`

The `if-else` logic is just determining which path to follow, the validation is already done
