### ISSUE TITLE
ADD: emissions to be based on emitted supply

### ISSUE THREAD

**Issue by strictly-scarce** [vetherasset/vaderprotocol-contracts#221]
For L2 plans, emissions to be decaying from a fixed daily amount (tail emissions), tweaked by governance, and based on the minted supply for that chain.

**Comment by Mervyn853** [comment]
This is a great idea. @Satoshi-Naoki will look into testing deployment on L2/sidechains and I will start reaching out for infrastructure like these and their foundational support for Vader Protocol.
