### ISSUE TITLE
DAO-01M: Dynamic Vote Weights

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#244]
**Description:**  
All vote weights and quorums are dynamically fetched, meaning that they can be substantially 
manipulated using flash loans and similar other mechanisms.

**Recommendation:**  
We strongly recommend each proposal to be attached to a time-based snapshot of the vote 
balances, similar to how other DAO implementations of dynamic supply tokens operate.

**Alleviation:**  
Although a lot of adjustments were made to the codebase, the concept still relies on the 
weights responded by the Vault implementation which themselves did not undergo any 
change and are manipulate-able.

This is going to be invalid once we have governor alpha merged.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
