### ISSUE TITLE
DAO-02M: Impermanent State Transitions

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#245]
**Description:** 
The state transitions that occur during the completion and cancellation of a proposal do not 
delete them from storage, allowing them to be voted on again and in the case of a cancellation 
to be executed.

**Recommendation:** 
We advise them to be completely wiped from memory to ensure state transitions are 
permanent.

**Alleviation:**
The cancellation of a proposal was rmeoved as a concept and bundled in the action of voting 
against a particular one. We should note the state transitions of the system still appear 
incorrect given that the  voteAgainstProposal  function can completely bypass the 
proposalFinalising  state as it can finalise a proposal directly.

Invalid once we have governor alpha.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
