### ISSUE TITLE
DAO-03M: Non-Informative Event

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#246]
**Description:**  
The  CancelProposal  event is only emitted when a previously submitted proposal is replaced 
by a new one, however, the new proposal's ID is not included in the event.

**Recommendation:** 
We strongly recommend the old proposal's ID to be included in the event.

**Alleviation:**  
The  CancelProposal  event was dropped entirely rendering the finding null.

Invalid once we have governor alpha.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
