### ISSUE TITLE
DAO-04M: Inexistent Input Sanitization

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#247]
**Description:**  
The  new  prefixed functions creating the various proposal types do not impose any form of 
input sanitization, permitting zero-value zero-address grants and different proposal types to 
created by different functions.

**Recommendation:**  
We advise the proposal creation functions to be revised, potentially applying some form of 
input sanitization to the various proposal parameters. If a minimum balance threshold or 
similar is applied, this exhibit is no longer necessary as it would deter misconfigured 
proposals.

**Alleviation:**  
The Vether - Vader Protocol development team has acknowledged this exhibit but decided to 
not apply its remediation in the current version of the codebase due to time constraints.

Invalid once we have governor alpha.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
