### ISSUE TITLE
DAO-05M: Potential Race Condition

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#248]
**Description:**  
The  newGrantProposal  function does not contain any access control and can be invoked by 
any member, thus allowing one to inspect the mempool for proposal creations and potentially 
race a proposal's creation if the attacker detects a proposal creation and vote in sequence.

**Recommendation:**  
We strongly recommend some form of access control to be imposed to proposal creations, 
such as a minimum balance, to ensure the system cannot be gamed or spammed.

**Alleviation:**  
A fee was introduced when creating a new proposal that disincentivizes this condition from 
arising.

Invalid once we have governor alpha.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
