### ISSUE TITLE
DAO-06M: Non-Standard  initinit  Pattern 

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#249]
**Description:**  
The  init  pattern is commonly utilized to initialize the storage space of a proxy 
implementation, however, here it is simply used to set initial values to the contract's variables.

**Recommendation:**  
We advise as many variables from the  init  function as possible to be initialized during the 
constructor  of the contract as that permits the utilization of the  immutable  mutability 
specifier which decreases read-access gas costs x20.

**Alleviation:**  
The Vether - Vader Protocol development team has acknowledged this exhibit but decided to 
not apply its remediation in the current version of the codebase due to time constraints.

Invalid once we have governor alpha.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
