### ISSUE TITLE
DAO-07M: Variable Mutability Specifier

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#250]
**Description:**  
The  coolOffPeriod  variable is assigned to only once during the contract's  constructor .

**Recommendation:**  
We strongly recommend the  immutable  mutability specifier to be included in the variable's 
declaration greatly optimizing its gas cost.

**Alleviation:**  
The variable is now adjusted by the  _setParams  function and thus cannot be optimized in 
this way.

Invalid once we have governor alpha merged.

**Comment by Satoshi-Naoki** [comment]
We converted DAO into Governor Alpha
