### ISSUE TITLE
FAC-01M: Redundant Contract Member

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#251]
**Description:**
The  _isSynth  mapping of the contract is redundant as evaluating whether the 
mapToken_Synth  is not equal to the zero-address achieves the same.

**Recommendation:**  
We advise mentions of the variable and the variable itself to be omitted from the codebase and 
the  isSynth  public function to instead utilize the same equality check as L28 of 
deploySynth .

**Alleviation:** 
The Vether - Vader Protocol development team has acknowledged this exhibit but decided to 
not apply its remediation in the current version of the codebase due to time constraints.

**Comment by Satoshi-Naoki** [comment]
This issue is a mistake of the auditor team.
mapToken_Synth is a mapping **token** to **synth**.
and isSynth is checking if **synth** is connected to any **token**.
But the audit team thought isSynth is checking if **token** is connected to any **synth**
