### ISSUE TITLE
FAC-02M: Simplification of Code

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#252]
**Description:**  
The  new Synth(token)  statement can immediately be cased to an  address  instead of being 
verbosely split into three statements.

**Recommendation:**  
We advise it to be done so to increase the legibility of the codebase.

**Alleviation:**  
Our recommendation was heeded and the cast is now performed directly.

**Comment by Satoshi-Naoki** [comment]
It's already fixed
old code
```
Synth newSynth;
newSynth = new Synth(token);
synth = address(newSynth);
```
updated code
```
synth = address(new Synth(token));
```
