### ISSUE TITLE
POO-02M: Inexistent Access Control of  basebase

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#254]
**Description:**  
The  base  is not sanitized in the  burnSynth  call allowing any token to be transferred out 
when burning a synth.

**Recommendation:**  
We strongly recommend proper validation to be imposed on the  base  argument of the 
function to ensure funds cannot be siphoned out of the system.

**Alleviation:**  
The  base  argument no longer exists and is assumed to be  USDV .

**Comment by Satoshi-Naoki** [comment]
The base argument doesn't exist in the current code
