### ISSUE TITLE
POO-04M: Usage of  tx.origintx.origin

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#256]
**Description:**  
The  removeLiquidity  function contains no access control and utilizes the  tx.origin  of a 
transaction call.

**Recommendation:**  
We strongly recommend the contract to instead accept an argument as the  tx.origin  
behaviour will change in an upcoming update to the EVM. Additionally, we advise some form 
of access control to be imposed on the function, perhaps as the previous exhibit states 
similarly to  addLiquidity , to ensure users cannot be tricked to remove their liquidity by 
malicious contracts.

**Alleviation:**  
Access control was introduced to the function and now the member to remove liquidity from is 
passed in as an argument thus ensuring that there is no usage of  tx.origin .

**Comment by Satoshi-Naoki** [comment]
**tx.origin** was already removed from removeLiquidity function
