### ISSUE TITLE
POO-08M: Inconsistent Access Control 

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#260]
**Description:**  
The  addLiquidity  function strictly evaluates that the  msg.sender  is the  ROUTER  and 
otherwise exposes the  addLiquidityDirectly  function whereas the  removeLiquidity  
function performs no such strict check and simply uses the  tx.origin .

**Recommendation:**  
We advise the  removeLiquidity  function to also impose the same  ROUTER  require check to 
ensure consistency in the codebase.

**Alleviation:**  
The  removeLiquidity  function now imposes the same level of access control.

**Comment by Satoshi-Naoki** [comment]
**addLiquidityDirectly** and **removeLiquidityDirectly** functions were removed.
**addLiquidity** and **removeLiquidity** functions were updated to be called by only the system.
