### ISSUE TITLE
RES-01M: Potentially Incorrect Return 

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#261]
**Description:**  
The  unallocatedVADER  function should return  0  if the  allocatedVADER  exceeds the 
currently held VADER.

**Recommendation:**  
If it indeed is intended to return the full balance in case the allocated VADER units exceed the 
currently held balance, we advise it to be documented so. Otherwise, we advise the linked 
assignment to be replaced by a zero-assignment one.

**Alleviation:**  
The function was adjusted to instead yield  0  if the allocated VADER exceed the reserve.

**Comment by Satoshi-Naoki** [comment]
It was already updated to return 0 when the allocated VADER exceed the reserve.
