### ISSUE TITLE
RES-03M: Statement Relocation

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#263]
**Description:**  
The  _reserve  variable is declared outside of the  if  block to enable the innermost  if  
statements to be replaced by a single  if  statement after the first one.

**Recommendation:**  
We advise it to be done so for optimizational reasons.

**Alleviation:**  
The optimization we recommended was applied to the codebase.

**Comment by Satoshi-Naoki** [comment]
It's already updated with single **if** statement

old code
```
if(base == VADER) {
    _reserve = reserveVADER();
    if(amount > _reserve){
        amount = _reserve;
    }
} else if(base == USDV()) {
    _reserve = reserveUSDV();
    if(amount > _reserve){
        amount = _reserve;
    }
}
```

updated code
```
if (base == VADER) {
    _reserve = reserveVADER();
} else if (base == USDV()) {
    _reserve = reserveUSDV();
}
if (amount > _reserve) {
    amount = _reserve;
}
```
