### ISSUE TITLE
ROU-01M: Malicious Pool Token Replacement

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#264]
**Description:**  
A user is able to flash loan the necessary amount of funds to procure enough base asset to 
replace a pool and anchor without sacrificing a large amount of funds, potentially causing the 
system to rely on a malicious token with re-entrancies etc. that allows full manipulate-ability of 
its reported values.

**Recommendation:**  
We strongly recommend the replacement notion to be revised and potentially dropped as it is 
not possible to properly filter malicious replacements in a decentralized fashion.

**Alleviation:**  
The replacement of a pool and anchor are now both guarded by the DAO thus preventing this 
scenario from unfolding.

**Comment by Satoshi-Naoki** [comment]
**replacePool** and **replaceAnchor** functions are both guarded by the **Timelock** now
