### ISSUE TITLE
ROU-03M: Incorrect TWAP Update Locations

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#266]
**Description:**  
The TWAP price of  VADER  to  USD  which is in turn retrieved by the Anchor feeds in 
getAnchorPrice  should be updated via the pool itself rather than the router as users are able 
to directly interface with the pool thus changing the prices without the price update being 
necessarily reflected in the router.

**Recommendation:**  
We strongly recommend the pool implementation to invoke the price updates of Router to 
ensure that the price is updated in all cases, including liquidity additions and removals as well 
as trades.

**Alleviation:**  
The  updateTWAPPrice  function was newly introduced in certain functions of the Router and 
additionally, the pool now has most functions privileged thus preventing price updates to 
occur without the TWAP being updated. We still recommend the extent of which this satisfies 
the intents and purposes of the system to be evaluated given that the code of the underlying 
Pool may change whereas our recommendation was a systematic change.

**Comment by Satoshi-Naoki** [comment]
regarding this, now Pools contract's functions such as **swap**, **mintSynth**, **burnSynth**, **addLiquidity**, **removeLiquidity**, etc are can be called by the only system.
So I think it's already solved.
@yellowgh0st how do you think about it?
