### ISSUE TITLE
POO-01S: Inexistent Visibility Specifiers

### ISSUE THREAD

**Issue by yellowgh0st** [vetherasset/vaderprotocol-contracts#273]
**Description:**  
The linked contract level variables have no visibility specifier explicitly set.

**Recommendation:**  
We advise one to be set as different compiler versions may yield different compilation outputs 
for the same codebase as currently a visibility is automatically assigned by the compiler.

**Alleviation:**  
Visibility specifiers were introduced for both linked variables.

**Comment by Satoshi-Naoki** [comment]
It's already updated and now the variables specify visibility.
