### ISSUE TITLE
Synth decimals

### ISSUE THREAD

**Issue by t4sk** [vetherasset/vaderprotocol-contracts#81]
Should Synth decimals equal token decimals?

https://github.com/vetherasset/vaderprotocol-contracts/blob/main/contracts/Synth.sol#L15

**Comment by yellowgh0st** [comment]
Ideally, it should get the _token decimals right?

**Comment by yellowgh0st** [comment]
Something like this
```
uint256 public override decimals = decimals;
decimals = string(abi.encodePacked(iERC20(_token).decimals();
```

**Comment by t4sk** [comment]
> Something like this
> 
> ```
> uint256 public override decimals = decimals;
> decimals = string(abi.encodePacked(iERC20(_token).decimals();
> ```

Not a string, but a `uint`
```soldity
decimals = iERC20(_token).decimals();
```

**Comment by strictly-scarce** [comment]
hmmm yes good point.
