### ISSUE TITLE
REMOVE: Anchor-SYNTHS

### ISSUE THREAD

**Issue by strictly-scarce** [vetherasset/vaderprotocol-contracts#86]
Remove ANCHOR-synth staking, so the only stablecoin to earn on is USDV, not USDT.v or USDC.v.

Also disable the option of creating SYNTHS from USDT, USDC, as well as allowing them to be used as collateral, thus, the only way to short something in the system (ie, borrow an asset with a stablecoin, this is shorting it) is to borrow against USDV.

So:
Synth-creation:
* Asset pools

Interest-Bearing:
* Asset-SYNTHS
* USDV

Loan Collateral:
* Asset-SYNTHS (longing the collateral asset)
* USDV (shorting the debt asset)
* VADER (longing VADER)

USDV should be a first-class citizen in the system, with all attention focussed on it.

**Comment by Mervyn853** [comment]
Reminder to remove VADER-USDV asset pool synth.

Not sure about IL protection? @strictly-scarce
