### ISSUE TITLE
REMOVE: token check inside USDV

### ISSUE THREAD

**Issue by t4sk** [vetherasset/vaderprotocol-contracts#94]
https://github.com/vetherasset/vaderprotocol-contracts/blob/main/contracts/USDV.sol#L201-L203

This can be removed since `getFunds` is only called with `VADER`

https://github.com/vetherasset/vaderprotocol-contracts/blob/main/contracts/USDV.sol#L172

**Comment by Mervyn853** [comment]
@0x1d00ffff I think the plan is only for VADER to be burned to mint USDV if i understand correctly. It is the only way you can acquire USDV without slippage outside of the pools.

**Comment by strictly-scarce** [comment]
Closing
